### ISSUE TITLE
Do not include hidden products in the sitemap

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-woocommerce#42] opened 2014-09-10 15:01 UTC
We received the following feedback from a customer:
"In Woocommerce you have the option to hide products from the Catalog.
From my understanding these hidden products also should NOT be included in the in the XML Sitemap that is generated by the Yoast SEO (Woocommerce) Plugin."

The option to hide a product from the catalog can be found in the publish-box on the edit-product-page.It's called Catalog visibility.

The customer adds:
"There is also a ready to use meta-query to query only visible products:
WC()->query->visibility_meta_query()
It is defined on line 595 in class-wc-query.php"

**Comment by omarreiss** [comment] 2015-03-30 12:38
Closing as duplicate of #60

**Comment by tacoverdo** [comment] 2015-04-08 06:18
I don't think this is a duplicate of #60, as it describes different functionality. Whereas #60 handles products that do not have certain attributes, this issue describes what should be done with products that are set to 'hidden'. 

@omarreiss can you please revisit this issue and help me understand if I'm wrong?

**Comment by teufelmartin** [comment] 2016-11-22 13:24
Any news on this issue?
Hidden products do still appear on sitemap.

**Comment by careofhaus** [comment] 2017-10-24 09:14
This one is still not fixed. Hidden products show up in the sitemap.

**Comment by aand01** [comment] 2017-12-06 15:36
Hi @omarreiss and @tacoverdo, this issue still lingers after being reported back in 2014 - could you please address this, so Woocommerce products hidden from the catalog do NOT appear in the sitemap?

Thanks,
- Asbjoern

**Comment by covaservices** [comment] 2018-01-28 12:22
Until the issue gets addresses, here's a function to remove hidden products from the sitemap, if product is only hidden from search, it still shows on sitemap. Also this will only work for Woo v3+ as I believe they changed they way visibility was handled with that update. 

You can add the below script to your functions.php file. 

Hope it helps someone :)


/* Remove Hidden from Catalog Products from Yoast Product Sitemap */
function cova_remove_hidden_products($url, $type, $post){
	if(is_object_in_term( $post->ID, 'product_visibility', 'exclude-from-catalog')){
		return '';
	}
	return $url;
}
add_filter( 'wpseo_sitemap_entry', 'cova_remove_hidden_products',99,3);

**Closed** 2018-06-22 11:52 UTC
Labels: SEO, bug, in progress, needs-acceptance, support
