### ISSUE TITLE
Content check broken

### ISSUE THREAD

**Issue by omarreiss** [Yoast/wpseo-woocommerce#123] opened 2016-06-13 10:19 UTC
When I go to a product page, I get the following analysis result:

![screen shot 2016-06-13 at 12 17 29](https://cloud.githubusercontent.com/assets/1488816/16004280/0c5fe318-3161-11e6-8f6f-dd64874c48b7.png)

**Comment by andizer** [comment] 2016-06-13 10:23
This is a duplicate of #120 and should be fixed in the meanwhile.

**Closed** 2016-06-13 10:23 UTC
Labels: bug, scheduled
