### ISSUE TITLE
Fatal error. The plugin cannot be activated because of fatal error.

### ISSUE THREAD

**Issue by ngrudev** [Yoast/wpseo-woocommerce#116] opened 2016-04-23 12:06 UTC
Warning: require_once(/home/lugabglj/public_html/bg_wp/wp-content/plugins/wpseo-woocommerce-trunk/class-product-wpseo-woocommerce.php): failed to open stream: No such file or directory in /home/lugabglj/public_html/bg_wp/wp-content/plugins/wpseo-woocommerce-trunk/wpseo-woocommerce.php on line 802

Fatal error: require_once(): Failed opening required '/home/lugabglj/public_html/bg_wp/wp-content/plugins/wpseo-woocommerce-trunk/class-product-wpseo-woocommerce.php' (include_path='.:/usr/local/php5.5/lib/php') in /home/lugabglj/public_html/bg_wp/wp-content/plugins/wpseo-woocommerce-trunk/wpseo-woocommerce.php on line 802

**Comment by 4mation-kyeates** [comment] 2016-06-01 04:03
I am having the same issue, looks like the classes are not being loaded from the class directory the code seems to be trying to load from the plugin root. 

the plugin does not even seem to try and load the options class before using it.

**Comment by jpittmanpc** [comment] 2016-07-31 06:54
same issue here.. i tried to remove that func & reinitialize the plugin, but it makes the site inoperable..

**Comment by boblinthorst** [comment] 2016-12-29 14:36
Hi, thank you for your bug report.

This is not something we can reproduce. We are able to install and activate the plugin without issues.

Looking at the error messages, it seems to be a problem with the setup, for which you'll need to contact your hosting provider. This issue will be closed as this is most likely not an issue on our end. If it however is an issue on our end, please reopen this issue with the current versions of the plugins you use and the steps to reproduce this issue.

**Closed by boblinthorst** 2016-12-29 14:36 UTC
