### ISSUE TITLE
Woocommerce seo bug with product variable

### ISSUE THREAD

**Issue by mredodos** [Yoast/wpseo-woocommerce#380] opened 2019-06-12 10:59 UTC
when I set up a product with variables. the following errors appear on the page

Fatal error: Uncaught Error: Class 'WPSEO_Schema_IDs' not found in /var/web/staging/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php:98 Stack trace: #0 /var/web/staging/public_html/wp-includes/class-wp-hook.php(286): WPSEO_WooCommerce_Schema->change_product(Array, Object(WC_Product_Variable)) #1 /var/web/staging/public_html/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array) #2 /var/web/staging/public_html/wp-content/plugins/woocommerce/includes/class-wc-structured-data.php(321): apply_filters('woocommerce_str...', Array, Object(WC_Product_Variable)) #3 /var/web/staging/public_html/wp-includes/class-wp-hook.php(286): WC_Structured_Data->generate_product_data(Object(WC_Product_Variable)) #4 /var/web/staging/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #5 /var/web/staging/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #6 /var/web/staging/public_html/wp-content/plugins/woocommerce/templates/content-single-product.php(60): in /var/web/staging/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php on line 98

word press and yoast last version

**Comment by Djennez** [comment] 2019-06-12 12:08
Hi, could you please follow our [Bug report](https://kb.yoast.com/kb/how-to-write-a-good-bug-report/) guidelines while submitting an issue? 

Please let us know which website this is about, and which versions (exactly) you are using of WordPress, Yoast and our Woocommerce addon.

**Comment by truchosky** [comment] 2019-06-30 07:01
guys, why so obtuse?, check this https://www.google.com/search?client=ubuntu&channel=fs&q=WPSEO_Schema_IDs+%2Fwoocommerce-schema.php%3A98&ie=utf-8&oe=utf-8

check all the sites with the same problem, I have the same issue, yoast 11.5 and woocommerce seo 11.4

**Comment by mredodos** [comment] 2019-06-30 16:48
sorry i dont have time to test, report, and follow the guide line. its simply error with woocommerce product variables. i have deactivated and i cant reactivate its on the client project.

You can reproduce on your test server.

**Comment by truchosky** [comment] 2019-06-30 17:02
error is not only with single products, with variable too

**Comment by Djennez** [comment] 2019-07-02 07:40
@mredodos Please use our GitHub issue trackers for documented bugreports only. We can't reproduce issues without further information. A normal installation with these three plugins works without issues so your installation has something that interferes with this. You can contact our support team if you have a premium subscription as they will be able to dive deeper into any issues your particular website may have.

@truchosky I noticed your replies on other related issues. If you have the same issue, please submit a [bugreport](https://kb.yoast.com/kb/how-to-write-a-good-bug-report/) or contact our support team. Adding these kinds of comments to other threads is not really helpful to the authors or to us.

**Comment by mredodos** [comment] 2019-07-02 08:25
the only probable difference with your tests is that mine is a multi-site installation.

I have disabled all plugins except those involved.

and the error appeared.

I wrote to the support but I haven't received any response for a month now.

I can't give more information than that because I had to find another solution to work and deactivate what didn't work.

if I could I would have done it.

**Comment by Djennez** [comment] 2019-07-02 09:36
> the only probable difference with your tests is that mine is a multi-site installation.

Hmmm, I was unable to replicate this on a multisite either. I'm afraid that's not specific enough.

> I wrote to the support but I haven't received any response for a month now.

That's odd. As you have a premium paid plugin you are entitled to support. Please [try to contact them again](https://kb.yoast.com/kb/support/#premium). I'll give them a heads up that they may expect an e-mail from you. You can reference this thread in your e-mail.

As this is not a valid bug report, and no more information can / will be given, I am closing this thread. If more information can be given we may be able to investigate this again. But your best bet is to contact support.

**Closed by Djennez** 2019-07-02 09:36 UTC
Labels: wait for feedback
