### ISSUE TITLE
Fatal error in case if Yoast SEO Woocommerce is  installed without Woocommerce plugin

### ISSUE THREAD

**Issue by annayoast** [Yoast/wpseo-woocommerce#906] opened 2023-04-28 14:21 UTC
* [X] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened
The issue is reproduced with realized Yoast SEO (Version 20.6) and  Yoast SEO: WooCommerce (Version 15.7 )
#### Step-by-step reproduction instructions
Precondition - Woocommerce plugin should be deactivated or deleted.
1. Install and activate Yoast SEO (Version 20.6) and  Yoast SEO: WooCommerce (Version 15.7 )
2. Open the Yoast SEO dashboard.

#### Expected results
1.  Customer can open Yoast SEO dashboard without errors.

#### Actual results
1. Fatal error 
![image](https://user-images.githubusercontent.com/117901794/235173493-0e1b1a28-db79-4fdb-b251-5c1aa63fb845.png)

### Screenshots, screen recording, code snippet
If possible, please provide a screenshot, a screen recording or a code snippet which demonstrates the bug.

### Technical info

* If relevant, which editor is affected (or editors): 
- [ ] Block Editor
- [ ] Gutenberg Editor
- [ ] Elementor Editor
- [ ] Classic Editor 
- [ ] Other: 

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other: 

#### Used versions
* Device you are using:
* Operating system:
* PHP version:
* WordPress version: 
* WordPress Theme:
* Yoast SEO version: 
* Yoast SEO for WooCommerce version:
* Gutenberg plugin version: 
* Elementor plugin version: 
* Classic Editor plugin version: 
* Relevant plugins in case of a bug:

**Comment by enricobattocchi** [comment] 2023-04-28 20:17
It's basically the same issue as https://github.com/Yoast/plugins-automated-testing/issues/603, but needs to be fixed for  other addons and not just for Local.
Reproduced with Free 20.0 and WooSEO 15.3 so not a recent regression (it's probably there since 19.10 at least)

**Comment by jeroenrotty** [comment] 2023-05-16 08:25
Was already fixed by https://github.com/Yoast/wordpress-seo/pull/20226 in 20.7. Closing.

**Closed by jeroenrotty** 2023-05-16 08:25 UTC
Labels: IM
