### ISSUE TITLE
Unable to Update SEO Title or Description Of Variable Products

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-woocommerce#65] opened 2015-06-16 01:12 UTC
The SEO title and description are not updating when a product has more than 40 variations **and** the WooCommerce SEO setting 'Move WooCommerce Up' is checked. Keeping variations under 40 per product or unchecking the 'Move WooCommerce Up' setting resolves the issue.

**Steps To Reproduce:**
1. Admin > SEO > WooCommerce SEO
2. Check 'Move WooCommerce Up' setting.
3. Save settings.
4. Create or edit a product.
5. Add 40+ variations, if needed.
6. Change the SEO title or description.
7. Save draft or publish item.

Current Outcome: Title and description retain previous data.
Expected Outcome: Title and description update to newly entered data. 

**Versions**
WordPress 4.2.2
WooCommerce SEO 1.1.6
WP SEO 2.2.1
WooCommerce 2.3.11

**Comment by amboutwe** [comment] 2015-06-16 01:13
Please inform the customer of conversation # 61249 when this issue has been closed.

**Comment by boblinthorst** [comment] 2016-12-28 13:21
Couldn't reproduce in the current version. Closing the issue.

**Closed by boblinthorst** 2016-12-28 13:21 UTC
Labels: bug, support

**Comment by vishalsengar** [comment] 2017-05-31 10:30
I am still experiencing the problem while using yoast, woocommerce and custom product tabs. As much as I noticed the error comes only when woocommerce custom product tabs is enabled with product custom tabs.
