### ISSUE TITLE
Variation products and grayed selection doesn't working right

### ISSUE THREAD

**Issue by gntoum** [Yoast/wpseo-woocommerce#157] opened 2017-06-29 10:16 UTC
### What did you expect to happen?
When i have a product with 2 attributes (size - color), and i have selected the "out of stock" products to be hidden, in my product view page, i expected when i choose the color of the product then the availables sizes to be selectable and the others grayed out. Also this must be refreshed if i change the color. 

### What happened instead?
Instead of this, when i select another color of the product, the available size selection remain the same from the previous color selection. I have to select and another size (if i am lucky and it's available) to be refresh the available options.

### How can we reproduce this behavior?
Create a variable product
Set 2 attributes (color - size)
Make variation foreach compination
Set a few variations out of stock and the other as in stock
Set in woocommerce settings page, the out of stock products to be hidden
Try to play with variation compinations in single product page

Can you provide a link to a page which shows this issue?
http://socialadvisor.gr/shefashion/product/pedilo-21/
### Technical info
* WordPress version: 4.8
* Yoast SEO version: -

**Comment by CarolineGeven** [comment] 2017-06-30 06:11
This is not a bug of [Yoast SEO WooCommerce](https://yoast.com/wordpress/plugins/yoast-woocommerce-seo/), but seems an issue with [WooCommerce](https://github.com/woocommerce/woocommerce/issues). As this is not related to our plugin, I'm closing this issue.

**Closed by CarolineGeven** 2017-06-30 06:11 UTC
