### ISSUE TITLE
Allow removing/changing anchor text for shop page in breadcrumbs

### ISSUE THREAD

**Issue by monbauza** [Yoast/wpseo-woocommerce#119] opened 2016-06-06 06:39 UTC
Right now no matter the permalinks used for products, the anchor text for the shop page always reads "_products_" in breadcrumbs

![image](https://cloud.githubusercontent.com/assets/9658774/15813671/2d54c6ec-2bc1-11e6-9721-e8bbb448d634.png)

**Comment by monbauza** [comment] 2016-06-06 06:47
Please inform the customer of conversation # 124017 when this conversation has been closed.

**Comment by monbauza** [comment] 2016-11-01 10:29
We have received a request from a customer to remove the shop page from breadcrumbs. The customer is not using the shop template. It'd be nice to have an option to hide the shop page (similar to the existng option to hide the blog page).

**Comment by monbauza** [comment] 2016-11-01 10:30
Please inform the customer of conversation # 156702 when this conversation has been closed.

**Comment by monbauza** [comment] 2017-04-24 06:09
Please inform the customer of conversation # 192176 when this conversation has been closed.

**Comment by monbauza** [comment] 2017-04-24 06:10
The above user would like to be able to remove "Products" from breadcrumbs.

**Comment by monbauza** [comment] 2017-05-15 07:14
Please inform the customer of conversation # 196544 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2017-05-29 15:00
related: https://github.com/Yoast/wordpress-seo/issues/7020

**Comment by Pcosta88** [comment] 2017-05-29 15:00
related: https://github.com/Yoast/wordpress-seo/issues/7179

**Comment by Pcosta88** [comment] 2017-05-29 15:03
Please inform the customer of conversation # 199179 when this conversation has been closed.

**Comment by suascat** [comment] 2017-07-01 14:49
Please inform the customer of conversation # 205495 when this conversation has been closed.

**Comment by suascat** [comment] 2017-12-07 08:01
Please inform the customer of conversation # 271489 when this conversation has been closed.

**Comment by Alie-Ammaar** [comment] 2018-04-01 19:49
please post the solution of this issue.

**Comment by rmarcano** [comment] 2018-04-18 01:25
Please inform the customer of conversation # 346195 when this conversation has been closed.

**Comment by iamazik** [comment] 2018-07-11 13:59
Please inform the customer of conversation # 403317 when this conversation has been closed.

**Comment by iamazik** [comment] 2018-07-11 14:33
@monbauza Looks like the issue no longer persists on Yoast SEO v7.8. I was unable to reproduce it anymore on my end.

![image 2018-07-11 at 8 29 32 pm](https://user-images.githubusercontent.com/8946603/42579196-957a1284-8549-11e8-8963-ad9905c55a16.png)
![image 2018-07-11 at 8 30 09 pm](https://user-images.githubusercontent.com/8946603/42579197-95e00c6a-8549-11e8-80e3-344bd113d616.png)
![image 2018-07-11 at 8 30 50 pm](https://user-images.githubusercontent.com/8946603/42579198-97115e2c-8549-11e8-9447-7607336814d9.png)

**Comment by benvaassen** [comment] 2018-07-12 06:20
Closing as the issue can't be reproduced with the newest version 7.8.

**Closed by benvaassen** 2018-07-12 06:20 UTC
Labels: enhancement, support
