### ISSUE TITLE
Schema markup only considers main product, not variations

### ISSUE THREAD

**Issue by galbaras** [Yoast/wpseo-woocommerce#655] opened 2020-12-03 01:57 UTC
### What did you expect to happen?

The Schema markup output for variable products should show all the available variations, and include both the regular price and the sale price for each variation.

It may be good to provide two options: "variations as product models" and "variations as offers". See discuss [here](https://www.schemaapp.com/newsletter/schema-org-variable-products-productmodels-offers/).

### What happened instead?

No variations are listed and the sale price appears as the regular price for variable products.

### How can we reproduce this behavior?

1. Create a variable product in WooCommerce without setting a regular or sales price.
2. Add variations with regular and sales prices
3. Check the Schema markup on the product page

Can you provide a link to a page which shows this issue?

https://dev.get-business-online.com/pacificsprings/product/prestige-spring-water-cooler/

### Technical info
* WordPress version: 5.5.3
* Yoast SEO version: 15.4
* Yoast SEO for WooCommerce version: 13.8

**Comment by Djennez** [comment] 2020-12-03 08:50
To prevent multiple threads about the same functionality I'm closing this as related to / duplicate of https://github.com/Yoast/wpseo-woocommerce/issues/508 and https://github.com/Yoast/featurerequests/issues/419 (internal only).

**Closed by Djennez** 2020-12-03 08:50 UTC
