### ISSUE TITLE
Fatal error: Call to undefined function is_product() 

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#344] opened 2019-04-15 12:08 UTC
### How can we reproduce this behavior?
1. Install and activate Yoast SEO 11.0 RC4.
2. Install and activate Yoast WooCommerce SEO 11.0 RC2.
3. Install and activate WooCommerce.
4. Set a Checkout Page on `WooCommerce` > `Settings` > `Advanced`, this can be any page.
5. Deactivate WooCommerce.
6. View the page you set as the checkout page.

Browse to Checkout page:

<img width="1806" alt="Screenshot 2019-04-15 at 14 07 52" src="https://user-images.githubusercontent.com/19681708/56131511-ec3aa200-5f87-11e9-8848-892294a00613.png">

**Comment by IreneStr** [comment] 2019-04-15 13:16
Solution: Yoast WooCommerce SEO should deactivate itself when WooCommerce is not active.

**Comment by laurasacco** [comment] 2019-04-18 09:42
Please inform the customer of conversation # 496087 when this conversation has been closed.

**Comment by michaldybczak** [comment] 2019-04-18 10:19
I have the same issue. After the update, the whole site just went white (I didn't deactivate woocommerce, it is a production site after all) and I had to roll back to the older plugins versions to fix it.

My php debug shows:

```
Fatal error: Uncaught Error: Call to undefined function is_product() in /home/akcesoriameblowe-online/public_html/wordpress/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php:54
Stack Trace
1.	WPSEO_WooCommerce_Schema->filter_webpage(Array)/home/akcesoriameblowe-online/public_html/wordpress/wp-includes/class-wp-hook.php:286
3.	apply_filters('wpseo_schema_we...', Array)/home/akcesoriameblowe-online/public_html/wordpress/wp-content/plugins/wordpress-seo-premium/frontend/schema/class-schema.php:70
4.	WPSEO_Schema->generate('')/home/akcesoriameblowe-online/public_html/wordpress/wp-includes/class-wp-hook.php:286
#6 /home/akcesoriameblowe-online/public in /home/akcesoriameblowe-online/public_html/wordpress/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php on line 54
```

Of course, I had a lot of similar entries in debug log.

**Comment by Xyfi** [comment] 2019-04-18 10:27
@michaldybczak Thank you for your report, the context regarding multisite is very helpful. We are currently working on this issue. Please keep following this issue for further progress on this issue.

**Comment by jdevalk** [comment] 2019-04-18 10:41
@michaldybczak we're going to fix this but in the meantime: why not only enable WooCommerce SEO on the site you have WooCommerce enabled on? That'll fix this.

**Comment by Xyfi** [comment] 2019-04-18 10:58
Fixed by #351

**Closed** 2019-04-18 10:58 UTC
Labels: regression

**Comment by michaldybczak** [comment] 2019-04-18 14:29
Awesome :).  I suspect that replacing wpseo-woocommerce.php from the last update with the git version that has the patch should fix it?
If not, I'll just wait for the official update. Now that I know that the problem is dealt with, I can calmly wait ;).

**Comment by jdevalk** [comment] 2019-04-18 16:29
@michaldybczak yes!

**Comment by michaldybczak** [comment] 2019-04-18 16:43
Thanks :)

**Comment by michaldybczak** [comment] 2019-04-18 16:51
I can confirm, the patch works. Updated Yoast and replaced wpseo-woocommerce.php with the one from git and all works correctly :).
Thanks again :).
