### ISSUE TITLE
'Remove Yoast SEO columns' does not remove the Link Counter columns

### ISSUE THREAD

**Issue by rmarcano** [Yoast/wpseo-woocommerce#174] opened 2017-10-18 03:13 UTC
### What did you expect to happen?
Once the 'Remove Yoast SEO columns', every Yoast SEO column should be removed from the Product Listing page and only leave the SEO Score column, as per the description on the page.

### What happened instead?
Every column was removed except the Text Link Counter columns.

### How can we reproduce this behavior?
1) Verify in the product listing page that all Yoast SEO columns are showing.
![before](https://user-images.githubusercontent.com/1044883/31699102-0b006e64-b38f-11e7-8a40-227e9b38be92.png)

2)Go to SEO -> Woocommerce SEO -> Select 'Remove Yoast SEO columns'
![remove](https://user-images.githubusercontent.com/1044883/31699305-42e0163a-b390-11e7-9f15-d62201f35307.png)

3) Verify that the Link Text Counter columns are not removed and SEO Score is not showing.
![after](https://user-images.githubusercontent.com/1044883/31699354-8a3ccb36-b390-11e7-9392-b949d44b6cf7.png)

Related:
https://github.com/Yoast/wpseo-woocommerce/issues/129
https://github.com/Yoast/wpseo-woocommerce/issues/136

### Technical info
* WordPress version: 4.8.2
* Yoast SEO version:  5.6.1
* Yoast WooCommerce SEO: 5.6

**Comment by rmarcano** [comment] 2017-10-18 03:14
Please inform the customer of conversation # 239737  when this conversation has been closed.

**Comment by Pcosta88** [comment] 2017-11-13 15:36
Please inform the customer of conversation # 258126 when this conversation has been closed.

**Comment by andizer** [comment] 2017-12-07 12:09
Duplicate of #162. This has been fixed in #178

**Closed by andizer** 2017-12-07 12:09 UTC
Labels: support
