### ISSUE TITLE
Duplicate og:image Meta Tags For Products

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-woocommerce#66] opened 2015-07-02 18:53 UTC
Duplicate og:image meta tags are generated for products with a photo gallery when WooCommerce SEO is active.

_Current Output with No Photo Gallery_
`<meta property="og:image" content="FEATURED_IMAGE"/>`

_Current Output with One Photo in the Photo Gallery_
`<meta property="og:image" content="FEATURED_IMAGE"/>`
`<meta property="og:image" content="FEATURED_IMAGE"/>`
`<meta property="og:image" content="GALLERY_IMAGE1"/>`

_Current Output with Three Photo in the Photo Gallery_
`<meta property="og:image" content="FEATURED_IMAGE"/>`
`<meta property="og:image" content="FEATURED_IMAGE"/>`
`<meta property="og:image" content="GALLERY_IMAGE1"/>`
`<meta property="og:image" content="FEATURED_IMAGE"/>`
`<meta property="og:image" content="GALLERY_IMAGE2"/>`
`<meta property="og:image" content="FEATURED_IMAGE"/>`
`<meta property="og:image" content="GALLERY_IMAGE3"/>`

_Expected Output_
Each image listed only once.

**To replicate:**
Create and save a product with at least one photo in the photo gallery.
View page source to see duplicate meta tags.

**Versions**
WP version: 4.2.2
WooCommerce SEO 1.1.6
WP SEO 2.2.1
WooCommerce 2.3.11

**Comment by boblinthorst** [comment] 2016-12-28 13:38
Checked with the current version. Couldn't reproduce. Probably fixed. Closing this issue.

**Closed by boblinthorst** 2016-12-28 13:38 UTC
Labels: bug, support
