### ISSUE TITLE
Wrong Image Meta Tags For Product Categories

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-woocommerce#71] opened 2015-08-25 22:36 UTC
Duplicate og:image tags and the wrong twitter image for WooCommerce product categories when a default image is set under Admin> SEO > Social > Facebook

[Screenshot](http://www.evernote.com/shard/s198/sh/dcd38599-f50d-417e-8c65-7d311a83c600/0bddcc86aec0e453960c1e04adadcee3)

**Current Output When Product Category Thumbnail is Selected**
`<meta property="og:image" content="DEFAULT_IMAGE" />`
`<meta property="og:image" content="THUMBNAIL_IMAGE" />`
{other metas}
`<meta property="og:image" content="DEFAULT_IMAGE" />`
{twitter metas}
`<meta name="twitter:image:src" content="DEFAULT_IMAGE"/>`

**Expected Output**
`<meta property="og:image" content="THUMBNAIL_IMAGE" />`
`<meta property="twitter:image:src" content="THUMBNAIL_IMAGE" />`

**Versions**
WP 4.3
WooSEO 1.1.6
SEO Prem 2.3.4
WooCommerce 2.4.6

Possibly related to #66

**Comment by omarreiss** [comment] 2016-07-19 08:33
We've slightly improved this behavior for 3.4. The default og:image tag is no longer duplicated, resulting into the current status:

**Current Output When Product Category Thumbnail is Selected**
`<meta property="og:image" content="DEFAULT_IMAGE" />`
`<meta property="og:image" content="THUMBNAIL_IMAGE" />`
{twitter metas}
`<meta name="twitter:image:src" content="DEFAULT_IMAGE"/>`

**Expected Output**
`<meta property="og:image" content="THUMBNAIL_IMAGE" />`
`<meta property="twitter:image:src" content="THUMBNAIL_IMAGE" />`

To get to the expected output, we need to change the way the og images are generated. This was not possible before 3.4

**Comment by aand01** [comment] 2016-11-10 13:21
I'm the one who originally reported this issue - and I'd just like to point out that it's now been more than 15 (FIFTEEN!!) months since this issue was reported, with no resolution in sight. Are you serious?

**Comment by aand01** [comment] 2016-11-16 18:03
Have you considered simply swapping the order the og:image entries appear in? If the 1st og:image encountered is always the one being used, your current approach will per definition always fetch the wrong image. Here's what you currently do:

<meta property="og:image" content="DEFAULT_IMAGE" />
<meta property="og:image" content="THUMBNAIL_IMAGE" />

and a simple change in the order could potentially solve the issue, ie:

<meta property="og:image" content="THUMBNAIL_IMAGE" />
<meta property="og:image" content="DEFAULT_IMAGE" />

What do you think?

**Comment by omarreiss** [comment] 2016-11-16 22:04
@aand01 first of all, I am really sorry you've had to wait this long without the issue being fixed. I can give you many reasons for why this is the case. But I also realize that doesn't make your experience with regard to this specific issue suck any less. So first things first.

I've queued this to be fixed in the coming weeks. We'll just go for a solution that fixes the Open Graph output instead of fixing the underlying architectural problem that caused the issue in the first place. 

Just to provide some context:

First time I saw this issue I thought it was easy to fix and couldn't believe it had been under our radar for a year already. In July, I think we ended up spending quite some hours to provide a fix and came up with a few small improvements but no fix. It turned out to be much more complicated than we imagined and we simply ran out of time. We did make plans for a more comprehensive refactor which would also solve this specific issue, but we didn't get to that yet because of other priorities and limited capacity. As said above, we'll try to come up with an intermediate solution now that just does the job and we'll deal with the underlying architecture later.

**Comment by aand01** [comment] 2017-01-03 11:24
Hi Omar, thanks for writing. What's the latest on this? And wouldn't swapping the order as suggested be a fix you could implement in practically minutes to resolve this? Ie this one:

From: 
```
<meta property="og:image" content="DEFAULT_IMAGE" />
<meta property="og:image" content="THUMBNAIL_IMAGE" />
```

to:


```
<meta property="og:image" content="THUMBNAIL_IMAGE" />
<meta property="og:image" content="DEFAULT_IMAGE" />
```

**Comment by aand01** [comment] 2017-01-18 15:41
@omarreiss What's the status on this? If my counting is correct, we're now at 17 months (and two months since your initial reply) without any apparent resolution.

**Comment by omarreiss** [comment] 2017-01-30 15:34
@aand01 It's actually sitting in our queue for two months now (which means it should have been fixed already). 

<img width="503" alt="seo_free___waffle_io" src="https://cloud.githubusercontent.com/assets/1488816/22429026/7eb57348-e709-11e6-90a0-4e666b7aee37.png"> 

Somehow it was still bypassed a couple of times by other issues that had a higher priority. As you have experienced, our capacity is limited. I've put this on top of the list now and I am assigning a developer this week to work on this. I'm sorry for your inconvenience.

**Comment by omarreiss** [comment] 2017-01-30 15:40
@andizer please fix this asap. It's probably easiest to create a filter in https://github.com/Yoast/wordpress-seo/blob/trunk/frontend/class-opengraph.php#L849 that simply allows you to filter `$this->images`. Then you can add the images there and the default image won't be rendered any more. It's not the prettiest solution, but it should fix this issue.

**Closed** 2017-02-01 12:20 UTC
Labels: acceptance, bug, support

**Comment by aand01** [comment] 2017-02-03 09:01
Thanks a lot for getting around to fixing it! Looking forward to the release

**Comment by Jon007** [comment] 2017-03-05 11:16
Hi, what's fixed in which version please?

The issue is still there for Product Categories in versions:

WP Version:		4.7.2
WooCommerce	 	by WooThemes – 2.6.14
Yoast SEO	 	by Team Yoast – 4.4

og:image and twitter:image meta headers are still filled with the fallback image rather than the product category image, unless you specifically go to Product Category, Yoast SEO, Social and explicitly set the image there, which seems to work as a workaround, but easy to forget to do, especially in the case of a multi-lingual installation where it may be necessary to repeat the process for each language, whereas normally the featured image is set once and synchronised.
Was the fix to allow this workaround to work?

**Comment by omarreiss** [comment] 2017-03-21 15:47
@Jon007 I couldn't reproduce the issue anymore.

I used Yoast WooCommerce SEO 4.5 and Yoast SEO 4.5 with WooCommerce 2.6.14

Please reach out to our support team if you need more assistance.
