### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by mahdi-alavi** [Yoast/wpseo-woocommerce#105] opened 2016-03-06 17:15 UTC
hi
after install and active:
Plugin could not be activated because it triggered a fatal error.

`Warning: require_once(D:\xampp\htdocs\wo\wp-content\plugins\wpseo-woocommerce/class-product-wpseo-woocommerce.php): failed to open stream: No such file or directory in D:\xampp\htdocs\wo\wp-content\plugins\wpseo-woocommerce\wpseo-woocommerce.php on line 782`

in line 782
`require_once( dirname( __FILE__ ) . '/class-product-wpseo-woocommerce.php' );`
after change to:
`require_once( dirname( __FILE__ ) . '/classes/class-product-wpseo-woocommerce.php' );`
After activating the plugin:
`Class 'WPSEO_Option_Woo' not found in D:\xampp\htdocs\wo\wp-content\plugins\wpseo-woocommerce\wpseo-woocommerce.php:70`

**Comment by boblinthorst** [comment] 2016-12-29 10:02
Hi, thank you for your bug report.

This is not something we can reproduce. We are able to install and activate the plugin without issues.

Looking at the error messages, it seems to be a problem with the setup, for which you'll need to contact your hosting provider. This issue will be closed as this is most likely not an issue on our end. If it however is an issue on our end, please reopen this issue with the current versions of the plugins you use and the steps to reproduce this issue.

**Closed by boblinthorst** 2016-12-29 10:02 UTC
